import streamlit as st
import os
import sqlite3
import glob
import time
import json
import re
import smtplib
from datetime import datetime
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import streamlit.components.v1 as components

# ==============================================================================
# 1. SYSTEM & DATABASE CONFIG
# ==============================================================================

try:
    __import__('pysqlite3')
    import sys
    sys.modules['sqlite3'] = sys.modules.pop('pysqlite3')
except ImportError:
    pass 

from langchain_google_genai import ChatGoogleGenerativeAI, GoogleGenerativeAIEmbeddings
from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.vectorstores import Chroma
from streamlit_mic_recorder import speech_to_text
from streamlit_google_auth import Authenticate

# Config
API_KEY = st.secrets["GEMINI_API_KEY"]
DATA_FOLDER = "DATA"
DB_PATH = "./chroma_db"
SQL_DB_FILE = "advocate_ai_v3.db"
MODEL_NAME = "gemini-2.5-flash" 

def send_email_report(receiver_email, case_name, content):
    """Sends the timeline to the user's login email"""
    try:
        sender_email = st.secrets["EMAIL_USER"]
        sender_password = st.secrets["EMAIL_PASS"]
        
        msg = MIMEMultipart()
        msg['From'] = f"Alpha Apex Legal <{sender_email}>"
        msg['To'] = receiver_email
        msg['Subject'] = f"Legal Timeline Report: {case_name}"
        
        body = f"Hello,\n\nPlease find below the extracted timeline for {case_name}:\n\n{content}\n\nThis report was generated by Alpha Apex AI."
        msg.attach(MIMEText(body, 'plain'))
        
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(sender_email, sender_password)
        server.send_message(msg)
        server.quit()
        return True
    except:
        return False

def init_sql_db():
    conn = sqlite3.connect(SQL_DB_FILE)
    c = conn.cursor()
    c.execute('CREATE TABLE IF NOT EXISTS users (email TEXT PRIMARY KEY, username TEXT, joined_date TEXT)')
    c.execute('CREATE TABLE IF NOT EXISTS cases (id INTEGER PRIMARY KEY AUTOINCREMENT, email TEXT, case_name TEXT, created_at TEXT)')
    c.execute('CREATE TABLE IF NOT EXISTS history (id INTEGER PRIMARY KEY AUTOINCREMENT, case_id INTEGER, role TEXT, content TEXT, timestamp TEXT)')
    conn.commit()
    conn.close()

def db_register_user(email, username):
    conn = sqlite3.connect(SQL_DB_FILE)
    c = conn.cursor()
    c.execute("INSERT OR IGNORE INTO users VALUES (?,?,?)", (email, username, datetime.now().strftime("%Y-%m-%d")))
    c.execute("SELECT count(*) FROM cases WHERE email=?", (email,))
    if c.fetchone()[0] == 0:
        c.execute("INSERT INTO cases (email, case_name, created_at) VALUES (?,?,?)", (email, "General Consultation", datetime.now().strftime("%Y-%m-%d")))
    conn.commit()
    conn.close()

def db_get_cases(email):
    conn = sqlite3.connect(SQL_DB_FILE)
    c = conn.cursor()
    c.execute("SELECT case_name FROM cases WHERE email=? ORDER BY id DESC", (email,))
    cases = [row[0] for row in c.fetchall()]
    conn.close()
    return cases if cases else ["General Consultation"]

def db_save_message(email, case_name, role, content):
    conn = sqlite3.connect(SQL_DB_FILE)
    c = conn.cursor()
    c.execute("SELECT id FROM cases WHERE email=? AND case_name=?", (email, case_name))
    res = c.fetchone()
    if res:
        c.execute("INSERT INTO history (case_id, role, content, timestamp) VALUES (?,?,?,?)", (res[0], role, content, datetime.now().strftime("%Y-%m-%d %H:%M:%S")))
    conn.commit()
    conn.close()

def db_load_history(email, case_name):
    conn = sqlite3.connect(SQL_DB_FILE)
    c = conn.cursor()
    c.execute("SELECT role, content FROM history JOIN cases ON history.case_id = cases.id WHERE cases.email=? AND cases.case_name=? ORDER BY history.id ASC", (email, case_name))
    data = [{"role": r, "content": t} for r, t in c.fetchall()]
    conn.close()
    return data

init_sql_db()

# ==============================================================================
# 2. UI, VOICE & AI
# ==============================================================================

st.set_page_config(page_title="Alpha Apex AI", page_icon="⚖️", layout="wide")

def play_voice_js(text, lang_code):
    safe_text = text.replace("'", "").replace('"', "").replace("\n", " ").strip()
    js_code = f"""
        <script>
            window.speechSynthesis.cancel();
            var msg = new SpeechSynthesisUtterance('{safe_text}');
            msg.lang = '{lang_code}';
            window.speechSynthesis.speak(msg);
        </script>
    """
    components.html(js_code, height=0)

@st.cache_resource
def load_models():
    llm = ChatGoogleGenerativeAI(model=MODEL_NAME, temperature=0.3, google_api_key=API_KEY)
    embed = GoogleGenerativeAIEmbeddings(model="models/embedding-001", google_api_key=API_KEY)
    return llm, embed

ai_engine, vector_embedder = load_models()

def sync_knowledge_base():
    if not os.path.exists(DATA_FOLDER): os.makedirs(DATA_FOLDER)
    pdfs = glob.glob(f"{DATA_FOLDER}/*.pdf")
    if os.path.exists(DB_PATH): return Chroma(persist_directory=DB_PATH, embedding_function=vector_embedder), "Ok"
    if pdfs:
        chunks = []
        for p in pdfs:
            loader = PyPDFLoader(p)
            chunks.extend(loader.load_and_split(RecursiveCharacterTextSplitter(chunk_size=2000, chunk_overlap=200)))
        return Chroma.from_documents(chunks, vector_embedder, persist_directory=DB_PATH), "Ready"
    return None, "Empty"

if "law_db" not in st.session_state:
    db_inst, _ = sync_knowledge_base()
    st.session_state.law_db = db_inst

# ==============================================================================
# 3. CHAMBERS (WITH EMAIL & TIMELINE)
# ==============================================================================

def render_chambers_page():
    languages = {
        "English": {"script": "English", "code": "en-US"},
        "Sindhi": {"script": "Sindhi script", "code": "sd-PK"},
        "Urdu": {"script": "Urdu script", "code": "ur-PK"},
        "Arabic": {"script": "Arabic", "code": "ar-SA"},
        "French": {"script": "French", "code": "fr-FR"},
        "Punjabi": {"script": "Punjabi script", "code": "pa-PK"},
        "Pashto": {"script": "Pashto script", "code": "ps-PK"}
    }

    with st.sidebar:
        st.header(f"👨‍⚖️ {st.session_state.username}")
        target_lang = st.selectbox("🌐 Response Language", options=list(languages.keys()))
        
        st.divider()
        st.subheader("📅 Expert Tools")
        history = db_load_history(st.session_state.user_email, st.session_state.active_case)
        
        if st.button("🕒 Extract Timeline"):
            if history:
                with st.spinner("Analyzing Case..."):
                    t_prompt = f"Create a chronological timeline of dates and legal events from this chat history: {' '.join([m['content'] for m in history])}"
                    st.session_state.timeline_data = ai_engine.invoke(t_prompt).content
                st.info(st.session_state.timeline_data)
            else: st.warning("No history found.")
        
        if "timeline_data" in st.session_state:
            if st.button("📧 Send Timeline to Email"):
                with st.spinner("Mailing..."):
                    if send_email_report(st.session_state.user_email, st.session_state.active_case, st.session_state.timeline_data):
                        st.success(f"Sent to {st.session_state.user_email}!")
                    else: st.error("Email failed. Check Secrets.")

        st.divider()
        cases = db_get_cases(st.session_state.user_email)
        if "active_case" not in st.session_state: st.session_state.active_case = cases[0]
        st.session_state.active_case = st.selectbox("Case Files", cases, index=cases.index(st.session_state.active_case))
        
        if st.button("Log Out"):
            st.session_state.logged_in = False
            st.rerun()

    st.title(f"💼 {st.session_state.active_case}")

    # Chat Display
    for msg in history:
        with st.chat_message(msg["role"]): st.markdown(msg["content"])

    # Input area
    c_text, c_mic = st.columns([10, 1])
    with c_text: text_in = st.chat_input(f"Consult Alpha Apex in {target_lang}...")
    with c_mic:
        voice_in = speech_to_text(language=languages[target_lang]["code"], key='mic', just_once=True)

    final_in = voice_in if voice_in else text_in
    if final_in:
        db_save_message(st.session_state.user_email, st.session_state.active_case, "user", final_in)
        with st.chat_message("user"): st.markdown(final_in)
        with st.chat_message("assistant"):
            ctx = ""
            if st.session_state.law_db:
                docs = st.session_state.law_db.as_retriever(search_kwargs={"k": 3}).invoke(final_in)
                ctx = "\n\n".join([d.page_content for d in docs])
            
            p = f"Senior Legal Expert. Respond ONLY in {languages[target_lang]['script']}.\nContext: {ctx}\nUser: {final_in}"
            res = ai_engine.invoke(p).content
            st.markdown(res)
            db_save_message(st.session_state.user_email, st.session_state.active_case, "assistant", res)
            play_voice_js(res, languages[target_lang]["code"])

# ==============================================================================
# 4. AUTH & MAIN (Restored Manual Login)
# ==============================================================================

# Initialize Google Auth
config_dict = dict(st.secrets["google_auth"])
secret_data = {"web": config_dict}
with open('client_secret.json', 'w') as f: json.dump(secret_data, f)
authenticator = Authenticate('client_secret.json', config_dict['redirect_uris'][0], 'adv_cookie', 'app_secret', 30)

if "logged_in" not in st.session_state: 
    st.session_state.logged_in = False

if not st.session_state.logged_in:
    c1, c2, c3 = st.columns([1, 2, 1])
    with c2:
        st.write("# ⚖️ Alpha Apex | Advocate AI")
        with st.container(border=True):
            st.subheader("Secure Login")
            authenticator.login() # Google Option
            
            st.divider()
            
            st.subheader("Manual Access")
            e = st.text_input("Enter your email")
            if st.button("Access Chambers"):
                if "@" in e and "." in e:
                    st.session_state.logged_in = True
                    st.session_state.user_email = e
                    st.session_state.username = e.split("@")[0].capitalize()
                    db_register_user(e, st.session_state.username)
                    st.success("Identity Verified.")
                    time.sleep(1)
                    st.rerun()
                else:
                    st.error("Invalid email.")
else:
    # Navigation logic
    with st.sidebar:
        nav = st.radio("Menu", ["🏢 Chambers", "📚 Library", "ℹ️ Team"])
    
    if nav == "🏢 Chambers":
        render_chambers_page()
    elif nav == "📚 Library":
        st.title("📚 Law Library")
        st.table([{"Doc": os.path.basename(f), "Status": "Ready"} for f in glob.glob(f"{DATA_FOLDER}/*.pdf")])
    else:
        st.title("ℹ️ Alpha Apex Team")
        st.info("Saim, Mustafa, Ibrahim, Huzaifa, Daniyal")
